### ISSUE TITLE
Implement repeating group (editgrid)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/formio-renderer#36]
See also: open-formulieren/open-forms#2441

**Tasks**

- [x] Implement React primitives/components
- [x] Find solution for icon library
- [x] Get MVP implementation that works for appointments flow & Formio component
- [x] Support validation errors & zod validation schema

**Expected properties/features for the formio component**

- [x] Nested components
- [x] `label`
- [x] `key`
- [x] `groupLabel`
- [x] `description`
- [ ] `tooltip` (postponed)
- [x] `hideLabel`
- [x] `disableAddingRemovingRows`
- [x] `addAnother` (text)
- [x] `saveRow` (text)
- [x] `removeRow` (text)

**Tougher challenges**

- [ ] Evaluate (conditional) visibility before rendering a nested component for each item
    - both the ValueDisplay
    - and the form field display
- [ ] Evaluating logic for an item inside the list of items
- [ ] Handle item-level validation errors (rather than errors about a field inside the item)
